/**
 * SEO-optimized, realistic demo listings for Karasu
 * Based on real market data and local neighborhoods
 */

export interface DemoListing {
  id: string;
  title: string;
  slug: string;
  location_neighborhood: string;
  location_district: string;
  location_full_address?: string;
  coordinates_lat: string;
  coordinates_lng: string;
  price_amount: string;
  price_currency: string;
  status: 'satilik' | 'kiralik';
  property_type: 'daire' | 'villa' | 'ev' | 'yazlik' | 'arsa' | 'isyeri' | 'dukkan';
  images: Array<{
    public_id: string;
    url: string;
    alt: string;
    order: number;
  }>;
  features: {
    rooms?: number;
    bathrooms?: number;
    sizeM2?: number;
    floor?: number;
    buildingAge?: number;
    heating?: string;
    furnished?: boolean;
    balcony?: boolean;
    parking?: boolean;
    elevator?: boolean;
    seaView?: boolean;
  };
  description_short: string;
  description_long: string;
  agent_name: string;
  agent_phone: string;
  agent_whatsapp: string;
  agent_email: string;
}

export const demoListings: DemoListing[] = [
  // SATILIK DAİRELER (1-6)
  {
    id: 'demo-1',
    title: 'Karasu Merkez Satılık 3+1 Deniz Manzaralı Daire - Yeni Yapı',
    slug: 'karasu-merkez-satilik-3-1-deniz-manzarali-daire-yeni-yapi',
    location_neighborhood: 'Merkez',
    location_district: 'Karasu',
    location_full_address: 'Karasu Merkez Mahallesi, Atatürk Caddesi, Sakarya',
    coordinates_lat: '41.0969',
    coordinates_lng: '30.7856',
    price_amount: '2850000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/daire-merkez-1',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
        alt: 'Karasu Merkez 3+1 Daire - Oturma Odası',
        order: 0,
      },
      {
        public_id: 'demo/daire-merkez-2',
        url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80',
        alt: 'Karasu Merkez 3+1 Daire - Mutfak',
        order: 1,
      },
      {
        public_id: 'demo/daire-merkez-3',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
        alt: 'Karasu Merkez 3+1 Daire - Deniz Manzarası',
        order: 2,
      },
    ],
    features: {
      rooms: 3,
      bathrooms: 2,
      sizeM2: 125,
      floor: 4,
      buildingAge: 3,
      heating: 'Kombi',
      furnished: false,
      balcony: true,
      parking: true,
      elevator: true,
      seaView: true,
    },
    description_short: 'Karasu Merkez\'de satılık 3+1 deniz manzaralı daire. Yeni yapı, asansörlü, otoparklı, kombi ile ısıtma.',
    description_long: 'Karasu Merkez Mahallesi\'nde, Atatürk Caddesi üzerinde satılık 3+1 deniz manzaralı daire. 3 yıllık yeni yapı, 4. kat, 125 m² kullanım alanı. Kombi ile ısıtma, geniş balkon, deniz manzarası, otopark ve asansör mevcut. Merkezi konumda, alışveriş merkezlerine ve sahil yürüyüş yoluna yürüme mesafesinde. Yatırım ve ikamet için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-2',
    title: 'Karasu Sahil Satılık 4+1 Lüks Daire - Denize Sıfır',
    slug: 'karasu-sahil-satilik-4-1-luks-daire-denize-sifir',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Sahil Yolu, Sakarya',
    coordinates_lat: '41.0975',
    coordinates_lng: '30.7870',
    price_amount: '4200000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/daire-sahil-1',
        url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
        alt: 'Karasu Sahil 4+1 Daire - Deniz Manzarası',
        order: 0,
      },
      {
        public_id: 'demo/daire-sahil-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
        alt: 'Karasu Sahil 4+1 Daire - Oturma Odası',
        order: 1,
      },
      {
        public_id: 'demo/daire-sahil-3',
        url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200&q=80',
        alt: 'Karasu Sahil 4+1 Daire - Yatak Odası',
        order: 2,
      },
    ],
    features: {
      rooms: 4,
      bathrooms: 3,
      sizeM2: 180,
      floor: 2,
      buildingAge: 5,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: true,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde denize sıfır satılık 4+1 lüks daire. Tam eşyalı, deniz manzaralı, otoparklı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize sıfır konumda satılık 4+1 lüks daire. 5 yıllık bina, 2. kat, 180 m² kullanım alanı. Tam eşyalı, kombi ile ısıtma, geniş balkon, panoramik deniz manzarası, kapalı otopark ve asansör mevcut. Sahil yürüyüş yoluna çıkış, plajlara yürüme mesafesinde. Yazlık ve yatırım için mükemmel seçenek.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-3',
    title: 'Karasu Çamlık Satılık 2+1 Daire - Sakin Bölge',
    slug: 'karasu-camlik-satilik-2-1-daire-sakin-bolge',
    location_neighborhood: 'Çamlık',
    location_district: 'Karasu',
    location_full_address: 'Karasu Çamlık Mahallesi, Çamlık Sokak, Sakarya',
    coordinates_lat: '41.0920',
    coordinates_lng: '30.7820',
    price_amount: '1850000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/daire-camlik-1',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
        alt: 'Karasu Çamlık 2+1 Daire - Oturma Odası',
        order: 0,
      },
      {
        public_id: 'demo/daire-camlik-2',
        url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=1200&q=80',
        alt: 'Karasu Çamlık 2+1 Daire - Mutfak',
        order: 1,
      },
    ],
    features: {
      rooms: 2,
      bathrooms: 1,
      sizeM2: 95,
      floor: 1,
      buildingAge: 8,
      heating: 'Kombi',
      furnished: false,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: false,
    },
    description_short: 'Karasu Çamlık Mahallesi\'nde satılık 2+1 daire. Sakin bölge, bahçeli, otoparklı, kombi ile ısıtma.',
    description_long: 'Karasu Çamlık Mahallesi\'nde, sakin bir sokakta satılık 2+1 daire. 8 yıllık bina, zemin kat, 95 m² kullanım alanı. Kombi ile ısıtma, balkon, bahçe kullanımı, otopark mevcut. Sakin ve huzurlu bir yaşam için ideal. Okullara ve marketlere yakın.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-4',
    title: 'Karasu Liman Satılık 3+1 Daire - Liman Manzaralı',
    slug: 'karasu-liman-satilik-3-1-daire-liman-manzarali',
    location_neighborhood: 'Liman',
    location_district: 'Karasu',
    location_full_address: 'Karasu Liman Mahallesi, Liman Caddesi, Sakarya',
    coordinates_lat: '41.0940',
    coordinates_lng: '30.7865',
    price_amount: '2200000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/daire-liman-1',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
        alt: 'Karasu Liman 3+1 Daire - Oturma Odası',
        order: 0,
      },
      {
        public_id: 'demo/daire-liman-2',
        url: 'https://images.unsplash.com/photo-1560448075-cbc16bb4af80?w=1200&q=80',
        alt: 'Karasu Liman 3+1 Daire - Balkon',
        order: 1,
      },
    ],
    features: {
      rooms: 3,
      bathrooms: 2,
      sizeM2: 135,
      floor: 3,
      buildingAge: 6,
      heating: 'Kombi',
      furnished: false,
      balcony: true,
      parking: true,
      elevator: true,
      seaView: true,
    },
    description_short: 'Karasu Liman Mahallesi\'nde satılık 3+1 liman manzaralı daire. Asansörlü, otoparklı, kombi ile ısıtma.',
    description_long: 'Karasu Liman Mahallesi\'nde, liman manzaralı satılık 3+1 daire. 6 yıllık bina, 3. kat, 135 m² kullanım alanı. Kombi ile ısıtma, geniş balkon, liman ve deniz manzarası, kapalı otopark ve asansör mevcut. Liman bölgesine yakın, balıkçı barınağına yürüme mesafesinde.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-5',
    title: 'Karasu Merkez Satılık 2+1 Daire - Uygun Fiyat',
    slug: 'karasu-merkez-satilik-2-1-daire-uygun-fiyat',
    location_neighborhood: 'Merkez',
    location_district: 'Karasu',
    location_full_address: 'Karasu Merkez Mahallesi, İnönü Caddesi, Sakarya',
    coordinates_lat: '41.0955',
    coordinates_lng: '30.7840',
    price_amount: '1650000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/daire-merkez-2-1',
        url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80',
        alt: 'Karasu Merkez 2+1 Daire - Oturma Odası',
        order: 0,
      },
      {
        public_id: 'demo/daire-merkez-2-2',
        url: 'https://images.unsplash.com/photo-1556912173-6714225b8887?w=1200&q=80',
        alt: 'Karasu Merkez 2+1 Daire - Yatak Odası',
        order: 1,
      },
    ],
    features: {
      rooms: 2,
      bathrooms: 1,
      sizeM2: 88,
      floor: 2,
      buildingAge: 12,
      heating: 'Kombi',
      furnished: false,
      balcony: true,
      parking: false,
      elevator: false,
      seaView: false,
    },
    description_short: 'Karasu Merkez\'de satılık 2+1 daire. Uygun fiyat, merkezi konum, kombi ile ısıtma, balkonlu.',
    description_long: 'Karasu Merkez Mahallesi\'nde, İnönü Caddesi üzerinde satılık 2+1 daire. 12 yıllık bina, 2. kat, 88 m² kullanım alanı. Kombi ile ısıtma, balkon mevcut. Merkezi konumda, alışveriş merkezlerine, okullara ve sağlık kuruluşlarına yakın. İlk ev alanlar için ideal seçenek.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-6',
    title: 'Karasu Sahil Satılık 5+2 Daire - Geniş Aile İçin',
    slug: 'karasu-sahil-satilik-5-2-daire-genis-aile-icin',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Yalı Caddesi, Sakarya',
    coordinates_lat: '41.0990',
    coordinates_lng: '30.7890',
    price_amount: '5500000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/daire-sahil-5-1',
        url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80',
        alt: 'Karasu Sahil 5+2 Daire - Geniş Oturma Odası',
        order: 0,
      },
      {
        public_id: 'demo/daire-sahil-5-2',
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80',
        alt: 'Karasu Sahil 5+2 Daire - Mutfak',
        order: 1,
      },
    ],
    features: {
      rooms: 5,
      bathrooms: 2,
      sizeM2: 220,
      floor: 1,
      buildingAge: 4,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: true,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde satılık 5+2 geniş daire. Deniz manzaralı, tam eşyalı, otoparklı, asansörlü.',
    description_long: 'Karasu Sahil Mahallesi\'nde, Yalı Caddesi üzerinde satılık 5+2 geniş daire. 4 yıllık yeni yapı, zemin kat, 220 m² kullanım alanı. Tam eşyalı, kombi ile ısıtma, geniş balkon, panoramik deniz manzarası, kapalı otopark ve asansör mevcut. Geniş aileler için ideal, bahçe kullanımı mümkün.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },

  // SATILIK VİLLALAR (7-11)
  {
    id: 'demo-7',
    title: 'Karasu Sahil Satılık Denize Sıfır Lüks Villa - 4+2',
    slug: 'karasu-sahil-satilik-denize-sifir-luks-villa-4-2',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Deniz Yolu, Sakarya',
    coordinates_lat: '41.0985',
    coordinates_lng: '30.7885',
    price_amount: '4800000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'villa',
    images: [
      {
        public_id: 'demo/villa-sahil-1',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
        alt: 'Karasu Sahil Denize Sıfır Villa - Dış Görünüm',
        order: 0,
      },
      {
        public_id: 'demo/villa-sahil-2',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
        alt: 'Karasu Sahil Villa - Bahçe',
        order: 1,
      },
      {
        public_id: 'demo/villa-sahil-3',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
        alt: 'Karasu Sahil Villa - İç Mekan',
        order: 2,
      },
    ],
    features: {
      rooms: 4,
      bathrooms: 2,
      sizeM2: 280,
      floor: 2,
      buildingAge: 7,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde denize sıfır satılık lüks villa. 4+2, geniş bahçeli, deniz manzaralı, tam eşyalı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize sıfır konumda satılık lüks villa. 7 yıllık yapı, 2 katlı, 280 m² kapalı alan, 400 m² bahçe. 4+2 oda, kombi ile ısıtma, geniş balkonlar, panoramik deniz manzarası, kapalı otopark, havuz alanı mevcut. Tam eşyalı, yazlık ve ikamet için mükemmel.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-8',
    title: 'Karasu Çamlık Satılık Bahçeli Villa - 3+1',
    slug: 'karasu-camlik-satilik-bahceli-villa-3-1',
    location_neighborhood: 'Çamlık',
    location_district: 'Karasu',
    location_full_address: 'Karasu Çamlık Mahallesi, Çam Sokak, Sakarya',
    coordinates_lat: '41.0915',
    coordinates_lng: '30.7815',
    price_amount: '3200000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'villa',
    images: [
      {
        public_id: 'demo/villa-camlik-1',
        url: 'https://images.unsplash.com/photo-1600585154526-990dbe4eb0a3?w=1200&q=80',
        alt: 'Karasu Çamlık Bahçeli Villa - Dış Görünüm',
        order: 0,
      },
      {
        public_id: 'demo/villa-camlik-2',
        url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80',
        alt: 'Karasu Çamlık Villa - İç Mekan',
        order: 1,
      },
    ],
    features: {
      rooms: 3,
      bathrooms: 2,
      sizeM2: 200,
      floor: 2,
      buildingAge: 10,
      heating: 'Kombi',
      furnished: false,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: false,
    },
    description_short: 'Karasu Çamlık Mahallesi\'nde satılık bahçeli villa. 3+1, geniş bahçe, otoparklı, sakin bölge.',
    description_long: 'Karasu Çamlık Mahallesi\'nde, sakin bir sokakta satılık bahçeli villa. 10 yıllık yapı, 2 katlı, 200 m² kapalı alan, 350 m² bahçe. 3+1 oda, kombi ile ısıtma, geniş balkon, kapalı otopark mevcut. Sakin ve huzurlu bir yaşam için ideal, doğa içinde.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-9',
    title: 'Karasu Sahil Satılık Yalı Villa - 5+3 Deniz Manzaralı',
    slug: 'karasu-sahil-satilik-yali-villa-5-3-deniz-manzarali',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Yalıevleri Sokak, Sakarya',
    coordinates_lat: '41.0960',
    coordinates_lng: '30.7875',
    price_amount: '6800000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'villa',
    images: [
      {
        public_id: 'demo/villa-yali-1',
        url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200&q=80',
        alt: 'Karasu Sahil Yalı Villa - Deniz Manzarası',
        order: 0,
      },
      {
        public_id: 'demo/villa-yali-2',
        url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=80',
        alt: 'Karasu Sahil Yalı Villa - Geniş Balkon',
        order: 1,
      },
    ],
    features: {
      rooms: 5,
      bathrooms: 3,
      sizeM2: 350,
      floor: 3,
      buildingAge: 5,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde satılık yalı villa. 5+3, deniz manzaralı, lüks, tam eşyalı, geniş bahçeli.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize sıfır konumda satılık yalı villa. 5 yıllık yeni yapı, 3 katlı, 350 m² kapalı alan, 500 m² bahçe. 5+3 oda, kombi ile ısıtma, geniş balkonlar, panoramik deniz manzarası, kapalı otopark, havuz mevcut. Tam eşyalı, lüks yaşam için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-10',
    title: 'Karasu Merkez Satılık Müstakil Villa - 4+2',
    slug: 'karasu-merkez-satilik-mustakil-villa-4-2',
    location_neighborhood: 'Merkez',
    location_district: 'Karasu',
    location_full_address: 'Karasu Merkez Mahallesi, Villa Sokak, Sakarya',
    coordinates_lat: '41.0965',
    coordinates_lng: '30.7850',
    price_amount: '3800000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'villa',
    images: [
      {
        public_id: 'demo/villa-merkez-1',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
        alt: 'Karasu Merkez Müstakil Villa - Dış Görünüm',
        order: 0,
      },
      {
        public_id: 'demo/villa-merkez-2',
        url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80',
        alt: 'Karasu Merkez Villa - İç Mekan',
        order: 1,
      },
    ],
    features: {
      rooms: 4,
      bathrooms: 2,
      sizeM2: 240,
      floor: 2,
      buildingAge: 8,
      heating: 'Kombi',
      furnished: false,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: false,
    },
    description_short: 'Karasu Merkez Mahallesi\'nde satılık müstakil villa. 4+2, bahçeli, otoparklı, merkezi konum.',
    description_long: 'Karasu Merkez Mahallesi\'nde, merkezi konumda satılık müstakil villa. 8 yıllık yapı, 2 katlı, 240 m² kapalı alan, 300 m² bahçe. 4+2 oda, kombi ile ısıtma, geniş balkon, kapalı otopark mevcut. Merkeze yakın, alışveriş ve hizmetlere kolay erişim.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-11',
    title: 'Karasu Sahil Satılık Modern Villa - 3+2',
    slug: 'karasu-sahil-satilik-modern-villa-3-2',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Modern Evler Sokak, Sakarya',
    coordinates_lat: '41.0978',
    coordinates_lng: '30.7880',
    price_amount: '4500000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'villa',
    images: [
      {
        public_id: 'demo/villa-modern-1',
        url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80',
        alt: 'Karasu Sahil Modern Villa - Dış Görünüm',
        order: 0,
      },
      {
        public_id: 'demo/villa-modern-2',
        url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200&q=80',
        alt: 'Karasu Sahil Modern Villa - İç Tasarım',
        order: 1,
      },
    ],
    features: {
      rooms: 3,
      bathrooms: 2,
      sizeM2: 260,
      floor: 2,
      buildingAge: 3,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde satılık modern villa. 3+2, yeni yapı, deniz manzaralı, tam eşyalı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, modern mimari ile tasarlanmış satılık villa. 3 yıllık yeni yapı, 2 katlı, 260 m² kapalı alan, 380 m² bahçe. 3+2 oda, kombi ile ısıtma, geniş balkonlar, deniz manzarası, kapalı otopark mevcut. Tam eşyalı, modern yaşam için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },

  // SATILIK YAZLIKLAR (12-14)
  {
    id: 'demo-12',
    title: 'Karasu Sahil Satılık Yazlık Ev - Denize Yakın 3+1',
    slug: 'karasu-sahil-satilik-yazlik-ev-denize-yakin-3-1',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Yazlık Evler Sokak, Sakarya',
    coordinates_lat: '41.0980',
    coordinates_lng: '30.7882',
    price_amount: '2800000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'yazlik',
    images: [
      {
        public_id: 'demo/yazlik-1',
        url: 'https://images.unsplash.com/photo-1600585154526-990dbe4eb0a3?w=1200&q=80',
        alt: 'Karasu Sahil Yazlık Ev - Dış Görünüm',
        order: 0,
      },
      {
        public_id: 'demo/yazlik-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
        alt: 'Karasu Sahil Yazlık Ev - İç Mekan',
        order: 1,
      },
    ],
    features: {
      rooms: 3,
      bathrooms: 2,
      sizeM2: 180,
      floor: 1,
      buildingAge: 12,
      heating: 'Klima',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde satılık yazlık ev. Denize yakın, 3+1, tam eşyalı, bahçeli, otoparklı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize yakın konumda satılık yazlık ev. 12 yıllık yapı, tek katlı, 180 m² kapalı alan, 250 m² bahçe. 3+1 oda, klima ile soğutma, geniş balkon, deniz manzarası, otopark mevcut. Tam eşyalı, yaz sezonu için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-13',
    title: 'Karasu Sahil Satılık Yazlık Villa - 4+2 Geniş',
    slug: 'karasu-sahil-satilik-yazlik-villa-4-2-genis',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Yazlık Villalar Sokak, Sakarya',
    coordinates_lat: '41.0972',
    coordinates_lng: '30.7878',
    price_amount: '3800000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'yazlik',
    images: [
      {
        public_id: 'demo/yazlik-villa-1',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
        alt: 'Karasu Sahil Yazlık Villa - Dış Görünüm',
        order: 0,
      },
      {
        public_id: 'demo/yazlik-villa-2',
        url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80',
        alt: 'Karasu Sahil Yazlık Villa - Bahçe',
        order: 1,
      },
    ],
    features: {
      rooms: 4,
      bathrooms: 2,
      sizeM2: 220,
      floor: 2,
      buildingAge: 8,
      heating: 'Klima',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde satılık yazlık villa. 4+2, geniş bahçeli, deniz manzaralı, tam eşyalı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize yakın konumda satılık yazlık villa. 8 yıllık yapı, 2 katlı, 220 m² kapalı alan, 400 m² bahçe. 4+2 oda, klima ile soğutma, geniş balkonlar, deniz manzarası, otopark mevcut. Tam eşyalı, geniş aileler için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-14',
    title: 'Karasu Sahil Satılık Denize Sıfır Yazlık - 2+1',
    slug: 'karasu-sahil-satilik-denize-sifir-yazlik-2-1',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Deniz Kenarı Sokak, Sakarya',
    coordinates_lat: '41.0995',
    coordinates_lng: '30.7895',
    price_amount: '2200000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'yazlik',
    images: [
      {
        public_id: 'demo/yazlik-sifir-1',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
        alt: 'Karasu Sahil Denize Sıfır Yazlık - Deniz Manzarası',
        order: 0,
      },
      {
        public_id: 'demo/yazlik-sifir-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
        alt: 'Karasu Sahil Denize Sıfır Yazlık - İç Mekan',
        order: 1,
      },
    ],
    features: {
      rooms: 2,
      bathrooms: 1,
      sizeM2: 140,
      floor: 1,
      buildingAge: 15,
      heating: 'Klima',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde denize sıfır satılık yazlık. 2+1, tam eşyalı, deniz manzaralı, otoparklı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize sıfır konumda satılık yazlık. 15 yıllık yapı, tek katlı, 140 m² kapalı alan, 200 m² bahçe. 2+1 oda, klima ile soğutma, geniş balkon, panoramik deniz manzarası, otopark mevcut. Tam eşyalı, yaz sezonu için mükemmel.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },

  // SATILIK ARSALAR (15-17)
  {
    id: 'demo-15',
    title: 'Karasu Sahil Satılık Yatırım Arsa - Denize Yakın',
    slug: 'karasu-sahil-satilik-yatirim-arsa-denize-yakin',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Arsa Parseli, Sakarya',
    coordinates_lat: '41.0970',
    coordinates_lng: '30.7872',
    price_amount: '850000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'arsa',
    images: [
      {
        public_id: 'demo/arsa-sahil-1',
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
        alt: 'Karasu Sahil Yatırım Arsa - Deniz Manzarası',
        order: 0,
      },
      {
        public_id: 'demo/arsa-sahil-2',
        url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80',
        alt: 'Karasu Sahil Arsa - Parsel Görünümü',
        order: 1,
      },
    ],
    features: {
      sizeM2: 600,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde satılık yatırım arsa. Denize yakın, 600 m², imarlı, yatırım için ideal.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize yakın konumda satılık yatırım arsa. 600 m² parsel, imarlı, yapılaşmaya uygun. Deniz manzaralı, yatırım ve villa yapımı için mükemmel konum. Altyapı mevcut, tapu hazır.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-16',
    title: 'Karasu Merkez Satılık İmarlı Arsa - Yapılaşmaya Uygun',
    slug: 'karasu-merkez-satilik-imarli-arsa-yapilasmya-uygun',
    location_neighborhood: 'Merkez',
    location_district: 'Karasu',
    location_full_address: 'Karasu Merkez Mahallesi, Arsa Parseli, Sakarya',
    coordinates_lat: '41.0958',
    coordinates_lng: '30.7845',
    price_amount: '550000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'arsa',
    images: [
      {
        public_id: 'demo/arsa-merkez-1',
        url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&q=80',
        alt: 'Karasu Merkez İmarlı Arsa - Parsel',
        order: 0,
      },
    ],
    features: {
      sizeM2: 450,
    },
    description_short: 'Karasu Merkez Mahallesi\'nde satılık imarlı arsa. 450 m², yapılaşmaya uygun, merkezi konum.',
    description_long: 'Karasu Merkez Mahallesi\'nde, merkezi konumda satılık imarlı arsa. 450 m² parsel, yapılaşmaya uygun, imar durumu net. Altyapı mevcut, tapu hazır. Daire veya villa yapımı için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-17',
    title: 'Karasu Çamlık Satılık Bahçeli Arsa - Doğa İçinde',
    slug: 'karasu-camlik-satilik-bahceli-arsa-doga-icinde',
    location_neighborhood: 'Çamlık',
    location_district: 'Karasu',
    location_full_address: 'Karasu Çamlık Mahallesi, Doğa Yolu, Sakarya',
    coordinates_lat: '41.0910',
    coordinates_lng: '30.7810',
    price_amount: '420000',
    price_currency: 'TRY',
    status: 'satilik',
    property_type: 'arsa',
    images: [
      {
        public_id: 'demo/arsa-camlik-1',
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
        alt: 'Karasu Çamlık Bahçeli Arsa - Doğa Manzarası',
        order: 0,
      },
    ],
    features: {
      sizeM2: 800,
    },
    description_short: 'Karasu Çamlık Mahallesi\'nde satılık bahçeli arsa. 800 m², doğa içinde, sakin bölge, villa yapımı için ideal.',
    description_long: 'Karasu Çamlık Mahallesi\'nde, doğa içinde satılık bahçeli arsa. 800 m² parsel, imarlı, villa yapımı için ideal. Sakin ve huzurlu bölge, doğa manzarası, altyapı mevcut.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },

  // KİRALIK DAİRELER (18-19)
  {
    id: 'demo-18',
    title: 'Karasu Merkez Kiralık 2+1 Daire - Uygun Fiyat',
    slug: 'karasu-merkez-kiralik-2-1-daire-uygun-fiyat',
    location_neighborhood: 'Merkez',
    location_district: 'Karasu',
    location_full_address: 'Karasu Merkez Mahallesi, Kiralık Evler Sokak, Sakarya',
    coordinates_lat: '41.0950',
    coordinates_lng: '30.7840',
    price_amount: '9500',
    price_currency: 'TRY',
    status: 'kiralik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/kiralik-daire-1',
        url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80',
        alt: 'Karasu Merkez Kiralık 2+1 Daire - Oturma Odası',
        order: 0,
      },
      {
        public_id: 'demo/kiralik-daire-2',
        url: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=1200&q=80',
        alt: 'Karasu Merkez Kiralık 2+1 Daire - Mutfak',
        order: 1,
      },
    ],
    features: {
      rooms: 2,
      bathrooms: 1,
      sizeM2: 85,
      floor: 1,
      buildingAge: 10,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: false,
      elevator: false,
      seaView: false,
    },
    description_short: 'Karasu Merkez Mahallesi\'nde kiralık 2+1 daire. Uygun fiyat, tam eşyalı, merkezi konum, kombi ile ısıtma.',
    description_long: 'Karasu Merkez Mahallesi\'nde, merkezi konumda kiralık 2+1 daire. 10 yıllık bina, 1. kat, 85 m² kullanım alanı. Tam eşyalı, kombi ile ısıtma, balkon mevcut. Merkeze yakın, alışveriş ve hizmetlere kolay erişim.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
  {
    id: 'demo-19',
    title: 'Karasu Sahil Kiralık 3+1 Daire - Deniz Manzaralı',
    slug: 'karasu-sahil-kiralik-3-1-daire-deniz-manzarali',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Kiralık Daireler Sokak, Sakarya',
    coordinates_lat: '41.0972',
    coordinates_lng: '30.7875',
    price_amount: '12500',
    price_currency: 'TRY',
    status: 'kiralik',
    property_type: 'daire',
    images: [
      {
        public_id: 'demo/kiralik-sahil-1',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
        alt: 'Karasu Sahil Kiralık 3+1 Daire - Deniz Manzarası',
        order: 0,
      },
      {
        public_id: 'demo/kiralik-sahil-2',
        url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80',
        alt: 'Karasu Sahil Kiralık 3+1 Daire - İç Mekan',
        order: 1,
      },
    ],
    features: {
      rooms: 3,
      bathrooms: 2,
      sizeM2: 110,
      floor: 3,
      buildingAge: 6,
      heating: 'Kombi',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: true,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde kiralık 3+1 daire. Deniz manzaralı, tam eşyalı, otoparklı, asansörlü.',
    description_long: 'Karasu Sahil Mahallesi\'nde, deniz manzaralı kiralık 3+1 daire. 6 yıllık bina, 3. kat, 110 m² kullanım alanı. Tam eşyalı, kombi ile ısıtma, geniş balkon, deniz manzarası, otopark ve asansör mevcut. Sahil yürüyüş yoluna yakın.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },

  // KİRALIK VİLLA/YAZLIK (20)
  {
    id: 'demo-20',
    title: 'Karasu Sahil Kiralık Yazlık Villa - Denize Sıfır 4+2',
    slug: 'karasu-sahil-kiralik-yazlik-villa-denize-sifir-4-2',
    location_neighborhood: 'Sahil',
    location_district: 'Karasu',
    location_full_address: 'Karasu Sahil Mahallesi, Kiralık Villalar Sokak, Sakarya',
    coordinates_lat: '41.0988',
    coordinates_lng: '30.7888',
    price_amount: '18000',
    price_currency: 'TRY',
    status: 'kiralik',
    property_type: 'villa',
    images: [
      {
        public_id: 'demo/kiralik-villa-1',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
        alt: 'Karasu Sahil Kiralık Yazlık Villa - Deniz Manzarası',
        order: 0,
      },
      {
        public_id: 'demo/kiralik-villa-2',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
        alt: 'Karasu Sahil Kiralık Yazlık Villa - Bahçe',
        order: 1,
      },
    ],
    features: {
      rooms: 4,
      bathrooms: 2,
      sizeM2: 200,
      floor: 2,
      buildingAge: 7,
      heating: 'Klima',
      furnished: true,
      balcony: true,
      parking: true,
      elevator: false,
      seaView: true,
    },
    description_short: 'Karasu Sahil Mahallesi\'nde denize sıfır kiralık yazlık villa. 4+2, tam eşyalı, geniş bahçeli, deniz manzaralı.',
    description_long: 'Karasu Sahil Mahallesi\'nde, denize sıfır konumda kiralık yazlık villa. 7 yıllık yapı, 2 katlı, 200 m² kapalı alan, 350 m² bahçe. 4+2 oda, klima ile soğutma, geniş balkonlar, panoramik deniz manzarası, otopark mevcut. Tam eşyalı, yaz sezonu için ideal.',
    agent_name: 'Karasu Emlak',
    agent_phone: '+905466395461',
    agent_whatsapp: '905466395461',
    agent_email: 'info@karasuemlak.net',
  },
];

