/**
 * KarasuEmlak.net Content Plan
 * 10 Cornerstones + 20 Blogs + Internal Linking Matrix
 *
 * Primary focus: Sapanca (4 CS) + Karasu (4 CS) + General (2 CS)
 * Preserve GSC verification meta + GA measurement ID exactly as-is.
 */

export type Intent = "informational" | "commercial" | "transactional" | "local";
export type FunnelStage = "TOFU" | "MOFU" | "BOFU";
export type CTAFocus = "ilan ara" | "iletişim" | "WhatsApp" | "ücretsiz danışmanlık";

export interface CornerstonePlan {
  id: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  intent: Intent;
  funnelStage: FunnelStage;
  targetAudience: string;
  uniqueAngle: string;
  seoTitle: string;
  h1: string;
  slug: string;
  parentCategory: "Karasu" | "Sapanca" | "Kocaali" | "General";
  mustAnswerQuestions: string[];
  microAnswerBlocks: string[];
  schema: string;
  ctaFocus: CTAFocus;
}

export interface BlogPlan {
  id: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  intent: Intent;
  funnelStage: FunnelStage;
  uniqueAngle: string;
  seoTitle: string;
  h1: string;
  slug: string;
  supportsCornerstone: string; // CS01..CS10
  microAnswerBlock: string;
  faqTopics: string[];
  ctaFocus: CTAFocus;
}

export interface LinkTarget {
  slug: string;
  anchor: string;
}

export const CORNERSTONES: CornerstonePlan[] = [
  // SAPANCA (4)
  {
    id: "CS01",
    primaryKeyword: "sapanca bungalov",
    secondaryKeywords: ["sapanca bungalov satılık", "sapanca bungalov kiralık", "sapanca bungalov fiyatları", "sapanca gölü bungalov"],
    intent: "commercial",
    funnelStage: "MOFU",
    targetAudience: "Tatil ve yatırım arayanlar, aileler",
    uniqueAngle: "Göl manzaralı bungalov seçenekleri + yatırım getirisi karşılaştırması",
    seoTitle: "Sapanca Bungalov Rehberi 2026: Satılık, Kiralık ve Fiyatlar",
    h1: "Sapanca Bungalov Rehberi: Satın Alma, Kiralama ve Yatırım",
    slug: "sapanca-bungalov-rehberi-satin-alma-kiralama-yatirim",
    parentCategory: "Sapanca",
    mustAnswerQuestions: [
      "Sapanca'da bungalov fiyatları ne kadar?",
      "Sapanca bungalov kiralık mı satılık mı almalı?",
      "Sapanca gölü çevresinde bungalov seçenekleri neler?",
      "Bungalov yatırımı karlı mı?",
    ],
    microAnswerBlocks: [
      "Sapanca bungalov fiyatları piyasa koşullarına göre değişir; aralık ver.",
      "Bungalov vs yazlık karşılaştırma tablosu.",
      "Göl çevresi mahalleler ve erişim bilgisi.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  {
    id: "CS02",
    primaryKeyword: "sapanca günlük kiralık",
    secondaryKeywords: ["sapanca günlük kiralık ev", "sapanca tatil evi", "sapanca haftalık kiralık", "sapanca konaklama"],
    intent: "transactional",
    funnelStage: "BOFU",
    targetAudience: "Tatil planlayanlar, hafta sonu kaçamak arayanlar",
    uniqueAngle: "Günlük/haftalık kiralık seçenekleri + rezervasyon ipuçları",
    seoTitle: "Sapanca Günlük Kiralık Evler 2026: Tatil ve Konaklama",
    h1: "Sapanca Günlük Kiralık Evler: Tatil ve Konaklama Rehberi",
    slug: "sapanca-gunluk-kiralik-evler-tatil-konaklama-rehberi",
    parentCategory: "Sapanca",
    mustAnswerQuestions: [
      "Sapanca'da günlük kiralık ev fiyatları ne kadar?",
      "Sapanca günlük kiralık nasıl bulunur?",
      "Sapanca'da hangi bölgeler tatil için uygun?",
    ],
    microAnswerBlocks: [
      "Günlük kiralık fiyat aralıkları (mevsimsel).",
      "Rezervasyon öncesi kontrol listesi.",
      "Sapanca aktiviteleri ve konaklama ilişkisi.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  {
    id: "CS03",
    primaryKeyword: "sapanca satılık daire",
    secondaryKeywords: ["sapanca daire fiyatları", "sapanca satılık", "sapanca daire", "sapanca göl manzaralı daire"],
    intent: "commercial",
    funnelStage: "MOFU",
    targetAudience: "Yatırımcılar, ikamet arayanlar",
    uniqueAngle: "Bölge analizi + daire vs bungalov karar rehberi",
    seoTitle: "Sapanca Satılık Daire Fiyatları ve Bölge Analizi 2026",
    h1: "Sapanca Satılık Daire: Fiyatlar, Bölgeler ve Yatırım Rehberi",
    slug: "sapanca-satilik-daire-fiyatlari-bolge-analizi-2026",
    parentCategory: "Sapanca",
    mustAnswerQuestions: [
      "Sapanca'da daire fiyatları ne kadar?",
      "Sapanca'da hangi mahalleler yatırım için uygun?",
      "Sapanca daire mi bungalov mu?",
    ],
    microAnswerBlocks: [
      "Daire fiyat aralıkları (m², bölge bazlı).",
      "Mahalle karşılaştırma tablosu.",
      "Tapu ve iskan durumu kontrol listesi.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  {
    id: "CS04",
    primaryKeyword: "sapanca satılık yazlık",
    secondaryKeywords: ["sapanca yazlık", "sapanca satılık yazlık ev", "sapanca yazlık fiyatları", "sapanca göl çevresi yazlık"],
    intent: "commercial",
    funnelStage: "MOFU",
    targetAudience: "Yazlık alıcıları, yatırımcılar",
    uniqueAngle: "Yazlık vs bungalov karşılaştırması + kira getirisi",
    seoTitle: "Sapanca Satılık Yazlık Rehberi ve Fiyatları 2026",
    h1: "Sapanca Satılık Yazlık: Fiyatlar ve Yatırım Rehberi",
    slug: "sapanca-satilik-yazlik-rehberi-fiyatlar-2026",
    parentCategory: "Sapanca",
    mustAnswerQuestions: [
      "Sapanca yazlık fiyatları ne kadar?",
      "Sapanca yazlık kira getirisi nasıl?",
      "Yazlık alırken hangi belgeleri kontrol etmeli?",
    ],
    microAnswerBlocks: [
      "Yazlık fiyat aralıkları.",
      "Kira getirisi hesaplama örneği.",
      "Tapu ve imar durumu kontrol listesi.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  // KARASU (4)
  {
    id: "CS05",
    primaryKeyword: "karasu satılık daire",
    secondaryKeywords: ["karasu daire fiyatları", "karasu satılık", "karasu daire", "karasu emlak daire"],
    intent: "commercial",
    funnelStage: "MOFU",
    targetAudience: "Yatırımcılar, ikamet arayanlar",
    uniqueAngle: "Sahil mahalleleri + denize yakınlık analizi",
    seoTitle: "Karasu Satılık Daire Fiyatları ve Mahalle Rehberi 2026",
    h1: "Karasu Satılık Daire: Fiyatlar, Mahalleler ve Rehber",
    slug: "karasu-satilik-daire-fiyatlari-mahalle-rehberi-2026",
    parentCategory: "Karasu",
    mustAnswerQuestions: [
      "Karasu'da daire fiyatları ne kadar?",
      "Karasu'da hangi mahalleler denize yakın?",
      "Karasu daire alırken dikkat edilecekler?",
    ],
    microAnswerBlocks: [
      "Sahil mahalleleri ve fiyat farkları.",
      "Mahalle karşılaştırma tablosu.",
      "İskan ve tapu kontrol listesi.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  {
    id: "CS06",
    primaryKeyword: "karasu kiralık daire",
    secondaryKeywords: ["karasu kiralık", "karasu kiralık ev", "karasu kiralık daire fiyatları", "karasu yaz kış kiralık"],
    intent: "commercial",
    funnelStage: "MOFU",
    targetAudience: "Kiracılar, yazlık arayanlar",
    uniqueAngle: "Yaz-kış kiralık farkları + sözleşme ipuçları",
    seoTitle: "Karasu Kiralık Daire Rehberi ve Fiyat Aralıkları 2026",
    h1: "Karasu Kiralık Daire: Fiyatlar ve Arama Rehberi",
    slug: "karasu-kiralik-daire-rehberi-fiyat-araliklari-2026",
    parentCategory: "Karasu",
    mustAnswerQuestions: [
      "Karasu kiralık daire fiyatları ne kadar?",
      "Karasu'da yazlık kiralık nasıl bulunur?",
      "Kiralık sözleşmesinde nelere dikkat edilmeli?",
    ],
    microAnswerBlocks: [
      "Kiralık fiyat aralıkları (mevsimsel).",
      "Kiralık arama kontrol listesi.",
      "Sözleşme maddeleri özeti.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  {
    id: "CS07",
    primaryKeyword: "karasu emlak",
    secondaryKeywords: ["karasu emlak ofisi", "karasu emlak piyasası", "karasu emlak danışmanlık", "karasu satılık kiralık"],
    intent: "commercial",
    funnelStage: "MOFU",
    targetAudience: "Alıcı, satıcı, yatırımcı",
    uniqueAngle: "Piyasa genel bakış + güvenilir danışmanlık kriterleri",
    seoTitle: "Karasu Emlak Piyasası 2026: Rehber ve Danışmanlık",
    h1: "Karasu Emlak: Piyasa Rehberi ve Danışmanlık",
    slug: "karasu-emlak-piyasasi-rehber-danismanlik-2026",
    parentCategory: "Karasu",
    mustAnswerQuestions: [
      "Karasu emlak piyasası nasıl?",
      "Karasu'da emlak alırken nelere dikkat edilmeli?",
      "Güvenilir emlak danışmanı nasıl seçilir?",
    ],
    microAnswerBlocks: [
      "Piyasa genel durumu (aralıklar).",
      "Emlak danışmanı seçim checklist.",
      "Tapu ve noter süreçleri özeti.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "CS08",
    primaryKeyword: "karasu kira getirisi",
    secondaryKeywords: ["karasu yazlık kira getirisi", "karasu yatırım getirisi", "karasu yazlık kiralama", "karasu emlak yatırım"],
    intent: "informational",
    funnelStage: "TOFU",
    targetAudience: "Yatırımcılar",
    uniqueAngle: "Yatırım getirisi hesaplama + risk faktörleri",
    seoTitle: "Karasu Kira Getirisi: Hesaplama ve Yatırım Rehberi 2026",
    h1: "Karasu Kira Getirisi: Hesaplama ve Yatırım Rehberi",
    slug: "karasu-kira-getirisi-hesaplama-yatirim-rehberi-2026",
    parentCategory: "Karasu",
    mustAnswerQuestions: [
      "Karasu'da kira getirisi ne kadar?",
      "Sahil mahallelerinde getiri farkı var mı?",
      "Yazlık kira getirisi nasıl hesaplanır?",
    ],
    microAnswerBlocks: [
      "Getiri hesaplama formülü ve örnek.",
      "Mahalle bazlı getiri karşılaştırması.",
      "Risk faktörleri listesi.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ilan ara",
  },
  // GENERAL (2)
  {
    id: "CS09",
    primaryKeyword: "emlak alırken kontrol listesi",
    secondaryKeywords: ["ev alırken dikkat edilecekler", "emlak alırken kontrol", "ev alırken tapu kontrol", "emlak alırken 7 şey"],
    intent: "informational",
    funnelStage: "TOFU",
    targetAudience: "İlk kez alıcılar",
    uniqueAngle: "7 maddelik kontrol listesi + tapu/iskan/imar",
    seoTitle: "Emlak Alırken Kontrol Listesi: 7 Kritik Madde",
    h1: "Emlak Alırken Kontrol Listesi: 7 Kritik Madde",
    slug: "emlak-alirken-kontrol-listesi-7-kritik-madde",
    parentCategory: "General",
    mustAnswerQuestions: [
      "Ev alırken hangi belgeleri kontrol etmeli?",
      "Tapu ve iskan durumu nasıl kontrol edilir?",
      "İmar durumu neden önemli?",
    ],
    microAnswerBlocks: [
      "7 maddelik checklist özeti.",
      "Tapu ve iskan farkı.",
      "En sık yapılan 5 hata.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "CS10",
    primaryKeyword: "sakarya yatırım rehberi",
    secondaryKeywords: ["sakarya emlak yatırım", "karasu sapanca yatırım", "sakarya yatırım bölgeleri", "emlak yatırım rehberi"],
    intent: "informational",
    funnelStage: "TOFU",
    targetAudience: "Yatırımcılar",
    uniqueAngle: "Karasu vs Sapanca vs Kocaali yatırım karşılaştırması",
    seoTitle: "Sakarya Emlak Yatırım Rehberi: Karasu, Sapanca, Kocaali",
    h1: "Sakarya Emlak Yatırım Rehberi: Karasu, Sapanca, Kocaali",
    slug: "sakarya-emlak-yatirim-rehberi-karasu-sapanca-kocaali",
    parentCategory: "General",
    mustAnswerQuestions: [
      "Sakarya'da nereye yatırım yapılmalı?",
      "Karasu mu Sapanca mı yatırım için uygun?",
      "Yatırım getirisi nasıl hesaplanır?",
    ],
    microAnswerBlocks: [
      "Bölge karşılaştırma tablosu.",
      "Getiri ve risk faktörleri.",
      "Hangi bölge kim için uygun.",
    ],
    schema: "Article + FAQPage",
    ctaFocus: "ücretsiz danışmanlık",
  },
];

export const BLOGS: BlogPlan[] = [
  {
    id: "BL01",
    primaryKeyword: "sapanca bungalov fiyatları",
    secondaryKeywords: ["sapanca bungalov kiralık fiyat", "sapanca bungalov satılık fiyat"],
    intent: "commercial",
    funnelStage: "MOFU",
    uniqueAngle: "Sapanca bungalov fiyat aralıkları ve mevsimsel değişim",
    seoTitle: "Sapanca Bungalov Fiyatları 2026: Kiralık ve Satılık",
    h1: "Sapanca Bungalov Fiyatları: Kiralık ve Satılık Aralıkları",
    slug: "sapanca-bungalov-fiyatlari-2026-kiralik-satilik",
    supportsCornerstone: "CS01",
    microAnswerBlock: "Sapanca bungalov fiyatları piyasa koşullarına göre değişir; günlük ve aylık aralıklar.",
    faqTopics: ["Sapanca bungalov günlük ne kadar?", "Satılık bungalov fiyatları?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL02",
    primaryKeyword: "sapanca gölü bungalov",
    secondaryKeywords: ["sapanca göl manzaralı bungalov", "sapanca göl kenarı konaklama"],
    intent: "commercial",
    funnelStage: "MOFU",
    uniqueAngle: "Göl manzaralı bungalov seçenekleri ve bölge rehberi",
    seoTitle: "Sapanca Gölü Bungalov: Göl Manzaralı Konaklama Seçenekleri",
    h1: "Sapanca Gölü Bungalov: Göl Manzaralı Konaklama",
    slug: "sapanca-golu-bungalov-gol-manzarali-konaklama",
    supportsCornerstone: "CS01",
    microAnswerBlock: "Sapanca Gölü çevresinde bungalov seçenekleri; mahalle ve erişim bilgisi.",
    faqTopics: ["Göl manzaralı bungalov fiyatları?", "Hangi mahalleler göl kenarı?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL03",
    primaryKeyword: "sapanca günlük kiralık fiyat",
    secondaryKeywords: ["sapanca tatil evi fiyat", "sapanca haftalık kiralık ne kadar"],
    intent: "transactional",
    funnelStage: "BOFU",
    uniqueAngle: "Günlük kiralık fiyat aralıkları (mevsimsel)",
    seoTitle: "Sapanca Günlük Kiralık Fiyatları 2026",
    h1: "Sapanca Günlük Kiralık Fiyatları 2026",
    slug: "sapanca-gunluk-kiralik-fiyatlari-2026",
    supportsCornerstone: "CS02",
    microAnswerBlock: "Sapanca günlük kiralık fiyatları mevsime göre değişir; aralık ver.",
    faqTopics: ["Günlük kiralık ortalama ne kadar?", "Hafta sonu fiyat farkı var mı?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL04",
    primaryKeyword: "sapanca tatil evi rezervasyon",
    secondaryKeywords: ["sapanca konaklama rezervasyon", "sapanca ev kiralamak"],
    intent: "transactional",
    funnelStage: "BOFU",
    uniqueAngle: "Rezervasyon öncesi kontrol listesi ve ipuçları",
    seoTitle: "Sapanca Tatil Evi Rezervasyon İpuçları",
    h1: "Sapanca Tatil Evi Rezervasyon İpuçları",
    slug: "sapanca-tatil-evi-rezervasyon-ipuclari",
    supportsCornerstone: "CS02",
    microAnswerBlock: "Sapanca tatil evi rezervasyonunda dikkat edilecek 5 madde.",
    faqTopics: ["Rezervasyon öncesi ne kontrol edilmeli?", "İptal koşulları nasıl?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL05",
    primaryKeyword: "sapanca daire fiyatları",
    secondaryKeywords: ["sapanca satılık daire", "sapanca daire m2 fiyat"],
    intent: "commercial",
    funnelStage: "MOFU",
    uniqueAngle: "m² bazlı fiyat analizi ve mahalle karşılaştırması",
    seoTitle: "Sapanca Daire Fiyatları m² ve Mahalle Analizi 2026",
    h1: "Sapanca Daire Fiyatları: m² ve Mahalle Analizi",
    slug: "sapanca-daire-fiyatlari-m2-mahalle-analizi-2026",
    supportsCornerstone: "CS03",
    microAnswerBlock: "Sapanca daire fiyatları m² ve Mahalle bazında değişir; aralık ver.",
    faqTopics: ["m² fiyatı ne kadar?", "En uygun mahalle hangisi?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL06",
    primaryKeyword: "sapanca bungalov mu daire mi",
    secondaryKeywords: ["sapanca daire bungalov karşılaştırma", "sapanca yatırım daire bungalov"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Daire vs bungalov karar matrisi",
    seoTitle: "Sapanca Bungalov mu Daire mi? Karar Rehberi",
    h1: "Sapanca Bungalov mu Daire mi? Karar Rehberi",
    slug: "sapanca-bungalov-mu-daire-mi-karar-rehberi",
    supportsCornerstone: "CS03",
    microAnswerBlock: "Sapanca'da bungalov ve daire karşılaştırması; kim için hangisi uygun.",
    faqTopics: ["Yatırım için hangisi?", "Tatil için hangisi?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL07",
    primaryKeyword: "sapanca yazlık kira getirisi",
    secondaryKeywords: ["sapanca yazlık kiralama", "sapanca yazlık yatırım"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Yazlık kira getirisi hesaplama örneği",
    seoTitle: "Sapanca Yazlık Kira Getirisi: Hesaplama ve Örnekler",
    h1: "Sapanca Yazlık Kira Getirisi: Hesaplama ve Örnekler",
    slug: "sapanca-yazlik-kira-getirisi-hesaplama-ornekler",
    supportsCornerstone: "CS04",
    microAnswerBlock: "Sapanca yazlık kira getirisi hesaplama formülü ve örnek senaryo.",
    faqTopics: ["Getiri oranı ne kadar?", "Mevsimsel fark var mı?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL08",
    primaryKeyword: "sapanca satılık bungalov",
    secondaryKeywords: ["sapanca bungalov satılık", "sapanca bungalov almak"],
    intent: "commercial",
    funnelStage: "MOFU",
    uniqueAngle: "Satılık bungalov alırken tapu ve imar kontrolü",
    seoTitle: "Sapanca Satılık Bungalov: Alırken Dikkat Edilecekler",
    h1: "Sapanca Satılık Bungalov: Alırken Dikkat Edilecekler",
    slug: "sapanca-satilik-bungalov-alirken-dikkat-edilecekler",
    supportsCornerstone: "CS04",
    microAnswerBlock: "Sapanca satılık bungalov alırken tapu, imar ve iskan kontrol listesi.",
    faqTopics: ["Tapu durumu nasıl kontrol edilir?", "İmar nedir?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL09",
    primaryKeyword: "karasu satılık daire mahalle",
    secondaryKeywords: ["karasu mahalle rehberi", "karasu sahil mahalleleri"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Mahalle bazlı daire fiyatı ve özellik karşılaştırması",
    seoTitle: "Karasu Satılık Daire: Mahalle Rehberi ve Fiyat Aralıkları",
    h1: "Karasu Satılık Daire: Mahalle Rehberi ve Fiyat Aralıkları",
    slug: "karasu-satilik-daire-mahalle-rehberi-fiyat-araliklari",
    supportsCornerstone: "CS05",
    microAnswerBlock: "Karasu mahalleleri ve daire fiyat aralıkları tablosu.",
    faqTopics: ["Sahil mahalleleri hangileri?", "En uygun mahalle?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL10",
    primaryKeyword: "karasu daire alırken dikkat",
    secondaryKeywords: ["karasu ev alırken", "karasu emlak tapu kontrol"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Karasu'da daire alırken 7 kontrol maddesi",
    seoTitle: "Karasu Daire Alırken Dikkat Edilecek 7 Madde",
    h1: "Karasu Daire Alırken Dikkat Edilecek 7 Madde",
    slug: "karasu-daire-alirken-dikkat-edilecek-7-madde",
    supportsCornerstone: "CS05",
    microAnswerBlock: "Karasu'da daire alırken tapu, iskan, aidat kontrol listesi.",
    faqTopics: ["İskan nedir?", "Tapu kontrolü nasıl yapılır?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL11",
    primaryKeyword: "karasu yaz kış kiralık fark",
    secondaryKeywords: ["karasu kiralık mevsimsel", "karasu yazlık kiralık"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Yaz-kış kiralık fiyat farkları ve sözleşme ipuçları",
    seoTitle: "Karasu Yaz-Kış Kiralık Daire Farkları",
    h1: "Karasu Yaz-Kış Kiralık Daire Farkları",
    slug: "karasu-yaz-kis-kiralik-daire-farklari",
    supportsCornerstone: "CS06",
    microAnswerBlock: "Karasu'da yaz ve kış kiralık fiyat farkları; sözleşme türleri.",
    faqTopics: ["Yazlık kiralık ne kadar?", "Kış fiyatları ne kadar?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL12",
    primaryKeyword: "karasu kiralık sözleşmesi",
    secondaryKeywords: ["karasu kira sözleşmesi", "kiralık ev sözleşme maddeleri"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Kiralık sözleşmesinde olması gereken maddeler",
    seoTitle: "Karasu Kiralık Daire Sözleşmesi: Bilmeniz Gerekenler",
    h1: "Karasu Kiralık Daire Sözleşmesi: Bilmeniz Gerekenler",
    slug: "karasu-kiralik-daire-sozlesmesi-bilmeniz-gerekenler",
    supportsCornerstone: "CS06",
    microAnswerBlock: "Kiralık sözleşmesinde olması gereken 5 temel madde.",
    faqTopics: ["Sözleşmede neler olmalı?", "Depozito nasıl belirlenir?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL13",
    primaryKeyword: "karasu emlak danışmanı seçimi",
    secondaryKeywords: ["güvenilir emlakçı", "karasu emlak ofisi"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Güvenilir emlak danışmanı seçim checklist",
    seoTitle: "Karasu Emlak Danışmanı Seçimi: 5 Kritik Kriter",
    h1: "Karasu Emlak Danışmanı Seçimi: 5 Kritik Kriter",
    slug: "karasu-emlak-danismani-secimi-5-kritik-kriter",
    supportsCornerstone: "CS07",
    microAnswerBlock: "Güvenilir emlak danışmanı seçerken 5 kontrol kriteri.",
    faqTopics: ["Nasıl güvenilir emlakçı bulunur?", "Komisyon oranı ne kadar?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL14",
    primaryKeyword: "karasu satılık daire tapu",
    secondaryKeywords: ["karasu tapu işlemleri", "karasu emlak noter"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Tapu ve noter süreçleri özeti",
    seoTitle: "Karasu Satılık Daire Tapu ve Noter İşlemleri",
    h1: "Karasu Satılık Daire Tapu ve Noter İşlemleri",
    slug: "karasu-satilik-daire-tapu-noter-islemleri",
    supportsCornerstone: "CS07",
    microAnswerBlock: "Karasu'da emlak alırken tapu ve noter süreçleri adımları.",
    faqTopics: ["Tapu devri ne kadar sürer?", "Noter masrafları ne kadar?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL15",
    primaryKeyword: "karasu yazlık fiyatları",
    secondaryKeywords: ["karasu yazlık satılık", "karasu yazlık kiralık"],
    intent: "commercial",
    funnelStage: "MOFU",
    uniqueAngle: "Karasu yazlık fiyat aralıkları ve bölge analizi",
    seoTitle: "Karasu Yazlık Fiyatları 2026: Satılık ve Kiralık",
    h1: "Karasu Yazlık Fiyatları 2026: Satılık ve Kiralık",
    slug: "karasu-yazlik-fiyatlari-2026-satilik-kiralik",
    supportsCornerstone: "CS08",
    microAnswerBlock: "Karasu yazlık fiyatları piyasa koşullarına göre değişir; aralık ver.",
    faqTopics: ["Yazlık fiyatları ne kadar?", "Sahil yazlık farkı var mı?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL16",
    primaryKeyword: "karasu kira getirisi hesaplama",
    secondaryKeywords: ["karasu yatırım getirisi", "emlak getiri hesaplama"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Getiri hesaplama formülü ve örnek senaryo",
    seoTitle: "Karasu Kira Getirisi Hesaplama: Formül ve Örnek",
    h1: "Karasu Kira Getirisi Hesaplama: Formül ve Örnek",
    slug: "karasu-kira-getirisi-hesaplama-formul-ornek",
    supportsCornerstone: "CS08",
    microAnswerBlock: "Kira getirisi = (yıllık kira / alış fiyatı) x 100; örnek hesaplama.",
    faqTopics: ["Getiri oranı nasıl hesaplanır?", "Vergi düşülür mü?"],
    ctaFocus: "ilan ara",
  },
  {
    id: "BL17",
    primaryKeyword: "ev alırken tapu kontrol",
    secondaryKeywords: ["tapu kontrolü nasıl yapılır", "tapu durumu sorgulama"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Tapu ve iskan durumu kontrol rehberi",
    seoTitle: "Ev Alırken Tapu ve İskan Kontrolü Nasıl Yapılır?",
    h1: "Ev Alırken Tapu ve İskan Kontrolü Nasıl Yapılır?",
    slug: "ev-alirken-tapu-iskan-kontrolu-nasil-yapilir",
    supportsCornerstone: "CS09",
    microAnswerBlock: "Tapu ve iskan durumu kontrol adımları; e-devlet sorgulama.",
    faqTopics: ["İskan nedir?", "Tapu rehberi nasıl okunur?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL18",
    primaryKeyword: "emlak alırken en sık yapılan hatalar",
    secondaryKeywords: ["ev alırken hatalar", "emlak alırken dikkat"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "5 yaygın hata ve nasıl kaçınılır",
    seoTitle: "Emlak Alırken En Sık Yapılan 5 Hata",
    h1: "Emlak Alırken En Sık Yapılan 5 Hata",
    slug: "emlak-alirken-en-sik-yapilan-5-hata",
    supportsCornerstone: "CS09",
    microAnswerBlock: "Emlak alırken yapılan 5 yaygın hata ve önleme yolları.",
    faqTopics: ["En sık hata hangisi?", "Nasıl kaçınılır?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL19",
    primaryKeyword: "karasu sapanca yatırım karşılaştırma",
    secondaryKeywords: ["karasu mı sapanca mı yatırım", "sakarya yatırım bölgeleri"],
    intent: "informational",
    funnelStage: "TOFU",
    uniqueAngle: "Karasu vs Sapanca yatırım karşılaştırma tablosu",
    seoTitle: "Karasu vs Sapanca Yatırım: Karşılaştırma Rehberi",
    h1: "Karasu vs Sapanca Yatırım: Karşılaştırma Rehberi",
    slug: "karasu-karsilastirma-sapanca-yatirim-rehberi",
    supportsCornerstone: "CS10",
    microAnswerBlock: "Karasu ve Sapanca yatırım karşılaştırması; getiri, risk, hedef kitle.",
    faqTopics: ["Hangisi daha karlı?", "Kim için hangisi uygun?"],
    ctaFocus: "ücretsiz danışmanlık",
  },
  {
    id: "BL20",
    primaryKeyword: "kocaali emlak yatırım",
    secondaryKeywords: ["kocaali satılık", "kocaali emlak piyasası"],
    intent: "commercial",
    funnelStage: "MOFU",
    uniqueAngle: "Kocaali emlak piyasası ve Sakarya karşılaştırması",
    seoTitle: "Kocaali Emlak Yatırımı: Piyasa ve Fırsatlar 2026",
    h1: "Kocaali Emlak Yatırımı: Piyasa ve Fırsatlar",
    slug: "kocaali-emlak-yatirimi-piyasa-firsatlar-2026",
    supportsCornerstone: "CS10",
    microAnswerBlock: "Kocaali emlak piyasası özeti; Karasu ve Sapanca ile karşılaştırma.",
    faqTopics: ["Kocaali fiyatları ne kadar?", "Yatırım potansiyeli var mı?"],
    ctaFocus: "ilan ara",
  },
];

export const LINKING_MATRIX = {
  pillarToBlogs: {
    CS01: [
      { slug: "sapanca-bungalov-fiyatlari-2026-kiralik-satilik", anchor: "Sapanca bungalov fiyatları" },
      { slug: "sapanca-golu-bungalov-gol-manzarali-konaklama", anchor: "göl manzaralı bungalov seçenekleri" },
    ],
    CS02: [
      { slug: "sapanca-gunluk-kiralik-fiyatlari-2026", anchor: "Sapanca günlük kiralık fiyatları" },
      { slug: "sapanca-tatil-evi-rezervasyon-ipuclari", anchor: "tatil evi rezervasyon ipuçları" },
    ],
    CS03: [
      { slug: "sapanca-daire-fiyatlari-m2-mahalle-analizi-2026", anchor: "Sapanca daire fiyatları" },
      { slug: "sapanca-bungalov-mu-daire-mi-karar-rehberi", anchor: "bungalov mu daire mi karar rehberi" },
    ],
    CS04: [
      { slug: "sapanca-yazlik-kira-getirisi-hesaplama-ornekler", anchor: "Sapanca yazlık kira getirisi" },
      { slug: "sapanca-satilik-bungalov-alirken-dikkat-edilecekler", anchor: "satılık bungalov alırken dikkat edilecekler" },
    ],
    CS05: [
      { slug: "karasu-satilik-daire-mahalle-rehberi-fiyat-araliklari", anchor: "Karasu mahalle rehberi" },
      { slug: "karasu-daire-alirken-dikkat-edilecek-7-madde", anchor: "daire alırken dikkat edilecekler" },
    ],
    CS06: [
      { slug: "karasu-yaz-kis-kiralik-daire-farklari", anchor: "yaz-kış kiralık farkları" },
      { slug: "karasu-kiralik-daire-sozlesmesi-bilmeniz-gerekenler", anchor: "kiralık sözleşmesi bilmeniz gerekenler" },
    ],
    CS07: [
      { slug: "karasu-emlak-danismani-secimi-5-kritik-kriter", anchor: "emlak danışmanı seçimi" },
      { slug: "karasu-satilik-daire-tapu-noter-islemleri", anchor: "tapu ve noter işlemleri" },
    ],
    CS08: [
      { slug: "karasu-yazlik-fiyatlari-2026-satilik-kiralik", anchor: "Karasu yazlık fiyatları" },
      { slug: "karasu-kira-getirisi-hesaplama-formul-ornek", anchor: "kira getirisi hesaplama" },
    ],
    CS09: [
      { slug: "ev-alirken-tapu-iskan-kontrolu-nasil-yapilir", anchor: "tapu ve iskan kontrolü" },
      { slug: "emlak-alirken-en-sik-yapilan-5-hata", anchor: "emlak alırken en sık yapılan hatalar" },
    ],
    CS10: [
      { slug: "karasu-karsilastirma-sapanca-yatirim-rehberi", anchor: "Karasu vs Sapanca yatırım karşılaştırması" },
      { slug: "kocaali-emlak-yatirimi-piyasa-firsatlar-2026", anchor: "Kocaali emlak yatırımı" },
    ],
  },
  crossPillarLinks: [
    { from: "CS04", to: "CS01", anchor: "Sapanca bungalov fırsatları" },
    { from: "CS01", to: "CS02", anchor: "Sapanca günlük kiralık seçenekleri" },
    { from: "CS02", to: "CS01", anchor: "Sapanca bungalov kiralama" },
    { from: "CS01", to: "CS04", anchor: "Sapanca satılık yazlık" },
    { from: "CS08", to: "CS05", anchor: "Karasu satılık daire" },
    { from: "CS05", to: "CS08", anchor: "Karasu kira getirisi" },
    { from: "CS10", to: "CS01", anchor: "Sapanca bungalov yatırımı" },
    { from: "CS10", to: "CS07", anchor: "Karasu emlak piyasası" },
  ],
};
