-- Q&A Entries for Content Completion
-- Generated: 2026-01-04T20:23:20.720Z
-- Total: 42 entries (21 Karasu + 21 Kocaali)

INSERT INTO public.qa_entries (question, answer, category, region, priority)
VALUES
  ('Karasu''da satılık ev fiyatları ne kadar?', 'Karasu''da satılık ev fiyatları konum, büyüklük ve özelliklere göre değişmektedir. Merkez bölgede 2+1 daireler genellikle 800.000 TL ile 1.500.000 TL arasında, denize yakın bölgelerde ise 1.200.000 TL ile 2.500.000 TL arasında değişmektedir. Müstakil evler ise 2.000.000 TL''den başlamaktadır.', 'bilgi', 'karasu', 'high'),
  ('Karasu''da emlak alırken nelere dikkat edilmeli?', 'Karasu''da emlak alırken konum, tapu durumu, yapı ruhsatı, denize mesafe, ulaşım imkanları ve çevresel faktörler önemlidir. Özellikle denize yakın bölgelerde sel riski kontrol edilmeli, tapu ve ruhsat belgeleri incelenmeli, çevredeki altyapı ve hizmetler değerlendirilmelidir.', 'bilgi', 'karasu', 'high'),
  ('Karasu''da hangi mahalleler yatırım için uygun?', 'Karasu''da yatırım potansiyeli yüksek mahalleler arasında Merkez, Sahil, Botağzı ve Yalı Mahallesi bulunmaktadır. Bu bölgeler denize yakınlık, ulaşım kolaylığı ve gelişen altyapı nedeniyle tercih edilmektedir. Ancak yatırım kararı vermeden önce detaylı piyasa araştırması yapılmalıdır.', 'yatirim', 'karasu', 'high'),
  ('Karasu''da kiralık ev bulmak kolay mı?', 'Karasu''da kiralık ev bulmak, özellikle yaz aylarında daha zor olabilir çünkü yazlıkçı talebi artmaktadır. Merkez bölgelerde daha fazla seçenek bulunurken, denize yakın bölgelerde kiralar daha yüksek olabilir. Kış aylarında daha fazla seçenek ve uygun fiyatlar bulunabilir.', 'bilgi', 'karasu', 'medium'),
  ('Karasu''da emlak komisyonu ne kadar?', 'Karasu''da emlak komisyonu genellikle satış fiyatının %2-3''ü arasında değişmektedir. Komisyon oranı emlak ofisine, işlemin büyüklüğüne ve hizmet kapsamına göre değişebilir. Detaylı bilgi için emlak ofisleri ile iletişime geçilmesi önerilir.', 'bilgi', 'karasu', 'medium'),
  ('Karasu merkezde satılık ev var mı?', 'Karasu merkezde satılık ev seçenekleri mevcuttur. Merkez bölgesi ulaşım, alışveriş ve hizmetlere yakınlık açısından avantajlıdır. Fiyatlar konum ve özelliklere göre değişmekle birlikte, merkez bölgede genellikle 800.000 TL ile 1.800.000 TL arasında seçenekler bulunmaktadır.', 'bilgi', 'karasu', 'high'),
  ('Karasu''da denize yakın satılık ev fiyatları nasıl?', 'Karasu''da denize yakın satılık ev fiyatları, denize mesafeye ve özelliklere göre değişmektedir. Denize sıfır veya çok yakın evler genellikle 1.500.000 TL''den başlamakta, lüks özellikli villalar ise 3.000.000 TL ve üzerinde olabilmektedir. Denize 500 metre mesafedeki evler ise 1.200.000 TL ile 2.000.000 TL arasında değişmektedir.', 'bilgi', 'karasu', 'high'),
  ('Karasu''da yatırımlık satılık ev almak mantıklı mı?', 'Karasu''da yatırımlık satılık ev almak, bölgenin turizm potansiyeli, denize yakınlık ve gelişen altyapı göz önüne alındığında değerlendirilebilir. Ancak yatırım kararı vermeden önce piyasa araştırması, kira getirisi analizi ve uzun vadeli planlama yapılmalıdır. Profesyonel danışmanlık alınması önerilir.', 'yatirim', 'karasu', 'high'),
  ('Karasu''da müstakil satılık ev bulmak zor mu?', 'Karasu''da müstakil satılık ev seçenekleri mevcuttur ancak dairelere göre daha az sayıdadır. Müstakil evler genellikle merkez dışındaki mahallelerde ve daha geniş arsalarda bulunmaktadır. Fiyatlar 2.000.000 TL''den başlamakta, özellik ve konuma göre artmaktadır.', 'bilgi', 'karasu', 'medium'),
  ('Karasu''da hangi bölgeler emlak yatırımı için uygun?', 'Karasu''da emlak yatırımı için değerlendirilebilecek bölgeler arasında denize yakın mahalleler, merkez bölge ve gelişmekte olan yeni yerleşim alanları bulunmaktadır. Yatırım kararı vermeden önce bölgenin altyapı durumu, ulaşım imkanları, turizm potansiyeli ve gelecek planları incelenmelidir.', 'yatirim', 'karasu', 'high'),
  ('Karasu''da emlak alım-satım süreci nasıl işler?', 'Karasu''da emlak alım-satım süreci genellikle şu adımları içerir: emlak seçimi, fiyat görüşmesi, sözleşme imzalanması, kapora ödenmesi, tapu işlemleri, kalan ödemenin yapılması ve tapu devri. Süreçte emlak ofisi, noter ve tapu müdürlüğü ile çalışılır. Tüm belgelerin kontrol edilmesi ve hukuki danışmanlık alınması önemlidir.', 'bilgi', 'karasu', 'medium'),
  ('Karasu''da yazlık ev almak mantıklı mı?', 'Karasu''da yazlık ev almak, yaz aylarında denize yakınlık ve doğal güzellikler açısından değerlendirilebilir. Ancak yazlık evlerin kış aylarında kullanımı sınırlı olabilir ve bakım maliyetleri dikkate alınmalıdır. Yatırım amaçlı alınıyorsa kira getirisi potansiyeli de değerlendirilmelidir.', 'yatirim', 'karasu', 'medium'),
  ('Karasu''da emlak kredisi alınabilir mi?', 'Karasu''da emlak kredisi alınabilir. Bankalar, uygun şartları sağlayan alıcılara konut kredisi verebilmektedir. Kredi başvurusu için gelir belgesi, kimlik belgesi ve tapu bilgileri gerekmektedir. Kredi oranı ve vadesi bankaya ve alıcının durumuna göre değişmektedir.', 'bilgi', 'karasu', 'low'),
  ('Karasu''da hangi mahalleler denize en yakın?', 'Karasu''da denize en yakın mahalleler arasında Sahil Mahallesi, Botağzı Bölgesi, Yalı Mahallesi ve Liman Bölgesi bulunmaktadır. Bu mahalleler denize 100-500 metre mesafede olup, deniz manzarası ve plaj erişimi açısından avantajlıdır.', 'bilgi', 'karasu', 'high'),
  ('Karasu''da emlak vergisi ne kadar?', 'Karasu''da emlak vergisi, emlakın değerine ve belediye tarafından belirlenen oranlara göre hesaplanmaktadır. Vergi oranları emlak tipine (konut, ticari, arsa) göre değişmektedir. Detaylı bilgi için Karasu Belediyesi ile iletişime geçilmesi önerilir.', 'bilgi', 'karasu', 'low'),
  ('Karasu''da satılık villa var mı?', 'Karasu''da satılık villa seçenekleri mevcuttur. Villalar genellikle denize yakın bölgelerde, geniş bahçeli ve lüks özellikli olarak bulunmaktadır. Fiyatlar 3.000.000 TL''den başlamakta, özellik ve konuma göre 10.000.000 TL ve üzerine çıkabilmektedir.', 'bilgi', 'karasu', 'medium'),
  ('Karasu''da emlak alırken noter gerekli mi?', 'Karasu''da emlak alım-satım işlemlerinde noter zorunluluğu bulunmaktadır. Sözleşme imzalanması, kapora ödenmesi ve tapu devri işlemleri noter huzurunda gerçekleştirilmelidir. Noter işlemleri güvenli ve hukuki bir alım-satım süreci için önemlidir.', 'bilgi', 'karasu', 'low'),
  ('Karasu''da hangi bölgeler daha güvenli?', 'Karasu genel olarak güvenli bir ilçedir. Merkez bölge, yerleşik nüfusun yoğun olduğu mahalleler ve denize yakın turistik bölgeler genellikle güvenli kabul edilmektedir. Ancak emlak alırken çevreyi incelemek, komşularla görüşmek ve bölge hakkında bilgi almak önemlidir.', 'bilgi', 'karasu', 'medium'),
  ('Karasu''da emlak alırken tapu kontrolü nasıl yapılır?', 'Karasu''da emlak alırken tapu kontrolü için tapu müdürlüğünden tapu kayıt örneği alınmalı, tapu üzerindeki bilgiler (ada, parsel, yüzölçümü, üzerindeki yapı) kontrol edilmelidir. Tapu üzerinde ipotek, haciz veya şerh olup olmadığı kontrol edilmeli, tapu sahibinin kimliği doğrulanmalıdır.', 'bilgi', 'karasu', 'low'),
  ('Karasu''da satılık arsa bulmak kolay mı?', 'Karasu''da satılık arsa seçenekleri mevcuttur. Arsa fiyatları konum, büyüklük, imar durumu ve denize mesafeye göre değişmektedir. Denize yakın arsalar daha pahalı olurken, merkez dışındaki arsalar daha uygun fiyatlı olabilmektedir. İmar durumu ve yapılaşma izinleri kontrol edilmelidir.', 'bilgi', 'karasu', 'low'),
  ('Karasu''da emlak alırken ekspertiz gerekli mi?', 'Karasu''da emlak alırken ekspertiz yaptırmak zorunlu değildir ancak önerilir. Ekspertiz, emlakın değerini, yapı durumunu, yasal durumunu ve risklerini değerlendirir. Özellikle yüksek değerli emlaklarda ve kredi kullanımında ekspertiz raporu istenebilir.', 'bilgi', 'karasu', 'low'),
  ('Kocaali''de satılık ev fiyatları ne kadar?', 'Kocaali''de satılık ev fiyatları konum ve özelliklere göre değişmektedir. Merkez bölgede 2+1 daireler genellikle 700.000 TL ile 1.300.000 TL arasında, denize yakın bölgelerde ise 1.000.000 TL ile 2.000.000 TL arasında değişmektedir. Müstakil evler 1.800.000 TL''den başlamaktadır.', 'bilgi', 'kocaali', 'high'),
  ('Kocaali''de emlak alırken nelere dikkat edilmeli?', 'Kocaali''de emlak alırken konum, tapu durumu, yapı ruhsatı, denize mesafe, ulaşım imkanları ve çevresel faktörler önemlidir. Özellikle denize yakın bölgelerde sel riski kontrol edilmeli, tapu ve ruhsat belgeleri incelenmeli, çevredeki altyapı ve hizmetler değerlendirilmelidir.', 'bilgi', 'kocaali', 'high'),
  ('Kocaali''de hangi mahalleler yatırım için uygun?', 'Kocaali''de yatırım potansiyeli yüksek mahalleler arasında Merkez, Sahil, Yalı ve Liman Mahallesi bulunmaktadır. Bu bölgeler denize yakınlık, ulaşım kolaylığı ve gelişen altyapı nedeniyle tercih edilmektedir. Ancak yatırım kararı vermeden önce detaylı piyasa araştırması yapılmalıdır.', 'yatirim', 'kocaali', 'high'),
  ('Kocaali''de kiralık ev bulmak kolay mı?', 'Kocaali''de kiralık ev bulmak, özellikle yaz aylarında daha zor olabilir çünkü yazlıkçı talebi artmaktadır. Merkez bölgelerde daha fazla seçenek bulunurken, denize yakın bölgelerde kiralar daha yüksek olabilir. Kış aylarında daha fazla seçenek ve uygun fiyatlar bulunabilir.', 'bilgi', 'kocaali', 'medium'),
  ('Kocaali''de emlak komisyonu ne kadar?', 'Kocaali''de emlak komisyonu genellikle satış fiyatının %2-3''ü arasında değişmektedir. Komisyon oranı emlak ofisine, işlemin büyüklüğüne ve hizmet kapsamına göre değişebilir. Detaylı bilgi için emlak ofisleri ile iletişime geçilmesi önerilir.', 'bilgi', 'kocaali', 'medium'),
  ('Kocaali merkezde satılık ev var mı?', 'Kocaali merkezde satılık ev seçenekleri mevcuttur. Merkez bölgesi ulaşım, alışveriş ve hizmetlere yakınlık açısından avantajlıdır. Fiyatlar konum ve özelliklere göre değişmekle birlikte, merkez bölgede genellikle 700.000 TL ile 1.500.000 TL arasında seçenekler bulunmaktadır.', 'bilgi', 'kocaali', 'high'),
  ('Kocaali''de denize yakın satılık ev fiyatları nasıl?', 'Kocaali''de denize yakın satılık ev fiyatları, denize mesafeye ve özelliklere göre değişmektedir. Denize sıfır veya çok yakın evler genellikle 1.200.000 TL''den başlamakta, lüks özellikli villalar ise 2.500.000 TL ve üzerinde olabilmektedir. Denize 500 metre mesafedeki evler ise 1.000.000 TL ile 1.800.000 TL arasında değişmektedir.', 'bilgi', 'kocaali', 'high'),
  ('Kocaali''de yatırımlık satılık ev almak mantıklı mı?', 'Kocaali''de yatırımlık satılık ev almak, bölgenin turizm potansiyeli, denize yakınlık ve gelişen altyapı göz önüne alındığında değerlendirilebilir. Ancak yatırım kararı vermeden önce piyasa araştırması, kira getirisi analizi ve uzun vadeli planlama yapılmalıdır. Profesyonel danışmanlık alınması önerilir.', 'yatirim', 'kocaali', 'high'),
  ('Kocaali''de müstakil satılık ev bulmak zor mu?', 'Kocaali''de müstakil satılık ev seçenekleri mevcuttur ancak dairelere göre daha az sayıdadır. Müstakil evler genellikle merkez dışındaki mahallelerde ve daha geniş arsalarda bulunmaktadır. Fiyatlar 1.800.000 TL''den başlamakta, özellik ve konuma göre artmaktadır.', 'bilgi', 'kocaali', 'medium'),
  ('Kocaali''de hangi bölgeler emlak yatırımı için uygun?', 'Kocaali''de emlak yatırımı için değerlendirilebilecek bölgeler arasında denize yakın mahalleler, merkez bölge ve gelişmekte olan yeni yerleşim alanları bulunmaktadır. Yatırım kararı vermeden önce bölgenin altyapı durumu, ulaşım imkanları, turizm potansiyeli ve gelecek planları incelenmelidir.', 'yatirim', 'kocaali', 'high'),
  ('Kocaali''de emlak alım-satım süreci nasıl işler?', 'Kocaali''de emlak alım-satım süreci genellikle şu adımları içerir: emlak seçimi, fiyat görüşmesi, sözleşme imzalanması, kapora ödenmesi, tapu işlemleri, kalan ödemenin yapılması ve tapu devri. Süreçte emlak ofisi, noter ve tapu müdürlüğü ile çalışılır. Tüm belgelerin kontrol edilmesi ve hukuki danışmanlık alınması önemlidir.', 'bilgi', 'kocaali', 'medium'),
  ('Kocaali''de yazlık ev almak mantıklı mı?', 'Kocaali''de yazlık ev almak, yaz aylarında denize yakınlık ve doğal güzellikler açısından değerlendirilebilir. Ancak yazlık evlerin kış aylarında kullanımı sınırlı olabilir ve bakım maliyetleri dikkate alınmalıdır. Yatırım amaçlı alınıyorsa kira getirisi potansiyeli de değerlendirilmelidir.', 'yatirim', 'kocaali', 'medium'),
  ('Kocaali''de emlak kredisi alınabilir mi?', 'Kocaali''de emlak kredisi alınabilir. Bankalar, uygun şartları sağlayan alıcılara konut kredisi verebilmektedir. Kredi başvurusu için gelir belgesi, kimlik belgesi ve tapu bilgileri gerekmektedir. Kredi oranı ve vadesi bankaya ve alıcının durumuna göre değişmektedir.', 'bilgi', 'kocaali', 'low'),
  ('Kocaali''de hangi mahalleler denize en yakın?', 'Kocaali''de denize en yakın mahalleler arasında Sahil Mahallesi, Yalı Mahallesi, Liman Bölgesi ve Plaj Bölgesi bulunmaktadır. Bu mahalleler denize 100-500 metre mesafede olup, deniz manzarası ve plaj erişimi açısından avantajlıdır.', 'bilgi', 'kocaali', 'high'),
  ('Kocaali''de emlak vergisi ne kadar?', 'Kocaali''de emlak vergisi, emlakın değerine ve belediye tarafından belirlenen oranlara göre hesaplanmaktadır. Vergi oranları emlak tipine (konut, ticari, arsa) göre değişmektedir. Detaylı bilgi için Kocaali Belediyesi ile iletişime geçilmesi önerilir.', 'bilgi', 'kocaali', 'low'),
  ('Kocaali''de satılık villa var mı?', 'Kocaali''de satılık villa seçenekleri mevcuttur. Villalar genellikle denize yakın bölgelerde, geniş bahçeli ve lüks özellikli olarak bulunmaktadır. Fiyatlar 2.500.000 TL''den başlamakta, özellik ve konuma göre 8.000.000 TL ve üzerine çıkabilmektedir.', 'bilgi', 'kocaali', 'medium'),
  ('Kocaali''de emlak alırken noter gerekli mi?', 'Kocaali''de emlak alım-satım işlemlerinde noter zorunluluğu bulunmaktadır. Sözleşme imzalanması, kapora ödenmesi ve tapu devri işlemleri noter huzurunda gerçekleştirilmelidir. Noter işlemleri güvenli ve hukuki bir alım-satım süreci için önemlidir.', 'bilgi', 'kocaali', 'low'),
  ('Kocaali''de hangi bölgeler daha güvenli?', 'Kocaali genel olarak güvenli bir ilçedir. Merkez bölge, yerleşik nüfusun yoğun olduğu mahalleler ve denize yakın turistik bölgeler genellikle güvenli kabul edilmektedir. Ancak emlak alırken çevreyi incelemek, komşularla görüşmek ve bölge hakkında bilgi almak önemlidir.', 'bilgi', 'kocaali', 'medium'),
  ('Kocaali''de emlak alırken tapu kontrolü nasıl yapılır?', 'Kocaali''de emlak alırken tapu kontrolü için tapu müdürlüğünden tapu kayıt örneği alınmalı, tapu üzerindeki bilgiler (ada, parsel, yüzölçümü, üzerindeki yapı) kontrol edilmelidir. Tapu üzerinde ipotek, haciz veya şerh olup olmadığı kontrol edilmeli, tapu sahibinin kimliği doğrulanmalıdır.', 'bilgi', 'kocaali', 'low'),
  ('Kocaali''de satılık arsa bulmak kolay mı?', 'Kocaali''de satılık arsa seçenekleri mevcuttur. Arsa fiyatları konum, büyüklük, imar durumu ve denize mesafeye göre değişmektedir. Denize yakın arsalar daha pahalı olurken, merkez dışındaki arsalar daha uygun fiyatlı olabilmektedir. İmar durumu ve yapılaşma izinleri kontrol edilmelidir.', 'bilgi', 'kocaali', 'low'),
  ('Kocaali''de emlak alırken ekspertiz gerekli mi?', 'Kocaali''de emlak alırken ekspertiz yaptırmak zorunlu değildir ancak önerilir. Ekspertiz, emlakın değerini, yapı durumunu, yasal durumunu ve risklerini değerlendirir. Özellikle yüksek değerli emlaklarda ve kredi kullanımında ekspertiz raporu istenebilir.', 'bilgi', 'kocaali', 'low');

-- Note: This uses ON CONFLICT DO NOTHING if unique constraint exists
-- If you want to update existing entries, use:
-- ON CONFLICT (question, region) DO UPDATE SET answer = EXCLUDED.answer, category = EXCLUDED.category, priority = EXCLUDED.priority;