-- Bulk insert Q&A entries for Karasu and Kocaali
-- Run this SQL directly in Supabase SQL Editor

INSERT INTO qa_entries (question, answer, category, priority, region) 
VALUES
-- KARASU Q&As (20)
('Karasu''da satılık ev almak mantıklı mı?', 'Evet, Karasu''da satılık ev almak mantıklıdır. İstanbul''a yakınlığı, denize yakın konumu, gelişen altyapısı ve turizm potansiyeli nedeniyle hem oturum hem yatırım amaçlı tercih edilebilir. Uzun vadede değer kazanma potansiyeli yüksektir.', 'karar_verme', 'high', 'karasu'),
('Karasu''da ev fiyatları neden değişken?', 'Karasu''da ev fiyatları konum, denize yakınlık, metrekare, oda sayısı, bina yaşı ve özelliklere göre değişmektedir. Denize yakın konumlar ve merkez mahalleler daha yüksek fiyatlara sahiptir. Ortalama fiyat aralığı 500.000 TL ile 3.000.000 TL arasındadır.', 'bilgi', 'high', 'karasu'),
('Karasu mu Kocaali mi yatırım için daha avantajlı?', 'Her iki bölge de kendine özgü avantajlar sunar. Karasu daha gelişmiş altyapı, yüksek turizm potansiyeli ve daha fazla sosyal tesis sunarken, Kocaali daha uygun giriş fiyatları ve sakin bir yaşam sunar. Yatırım tercihi bütçe ve hedeflere göre değişir.', 'karsilastirma', 'high', 'karasu'),
('Karasu''da ev alırken en çok yapılan hatalar nelerdir?', 'Yeterli araştırma yapmamak, tapu durumunu kontrol etmemek, denize mesafeyi yanlış değerlendirmek, kış aylarında bakım maliyetlerini göz ardı etmek ve profesyonel danışmanlık almamak yaygın hatalardır. Dikkatli bir yaklaşım önemlidir.', 'risk', 'high', 'karasu'),
('Denize yakın evler gerçekten değer kazandırır mı?', 'Evet, denize yakın evler genellikle daha yüksek değer artışı gösterir. Turizm potansiyeli, yazlık kiralama geliri ve talep yüksekliği nedeniyle uzun vadede değer kazanma potansiyeli yüksektir. Ancak bakım maliyetleri de dikkate alınmalıdır.', 'yatirim', 'high', 'karasu'),
('Karasu''da hangi mahalleler yatırım için uygundur?', 'Denize yakın mahalleler (Sahil, Yalı Mahallesi) ve merkez konumlar yatırım potansiyeli açısından öne çıkar. Yeni konut projelerinin olduğu bölgeler de uzun vadeli yatırım için uygundur. Her mahallenin kendine özgü avantajları vardır.', 'yatirim', 'medium', 'karasu'),
('Karasu''da ev alırken tapu süreci nasıl işler?', 'Tapu süreci genellikle 1-2 hafta sürer. Satıcı ve alıcı noterde buluşur, tapu devri yapılır. Gerekli belgeler: kimlik, vergi levhası, tapu, ruhsat. Profesyonel emlak danışmanı tüm süreci yönetir ve güvenli bir işlem sağlar.', 'bilgi', 'medium', 'karasu'),
('Karasu''da yazlık mı sürekli oturumluk ev mi tercih edilmeli?', 'Tercih, yaşam tarzı ve bütçeye göre değişir. Yazlık evler yatırım ve tatil amaçlı uygundur. Sürekli oturum için merkeze yakın, altyapısı gelişmiş mahalleler tercih edilmelidir. Her iki seçenek de Karasu''da mevcuttur.', 'karar_verme', 'medium', 'karasu'),
('Karasu''da ev fiyatları gelecekte artacak mı?', 'İstanbul''a yakınlık, turizm potansiyeli, altyapı yatırımları ve talep artışı uzun vadede fiyat artışı sağlayabilir. Ancak piyasa koşulları değişkendir. Güncel analiz için profesyonel danışmanlık alınması önerilir.', 'yatirim', 'medium', 'karasu'),
('Karasu''da ev alırken nelere dikkat edilmeli?', 'Konum, fiyat, bina yaşı, yapı durumu, tapu durumu, denize yakınlık, ulaşım imkanları, sosyal altyapı ve gelecekteki projeler dikkate alınmalıdır. Profesyonel emlak danışmanı ile çalışmak önemlidir.', 'risk', 'high', 'karasu'),
('Karasu''da kredi ile ev alınabilir mi?', 'Evet, Karasu''da kredi ile ev alınabilir. Banka kredisi ve peşinat seçenekleri mevcuttur. Genellikle ev değerinin %70-80''i kadar kredi kullanılabilir. Kredi başvuru süreci ve onay koşulları için emlak danışmanınızla görüşebilirsiniz.', 'bilgi', 'medium', 'karasu'),
('Karasu''da hangi ev türleri daha popüler?', 'Müstakil evler, daireler, villalar ve yazlık evler popülerdir. Denize yakın konumlarda yazlık evler ve villalar, merkez bölgelerde daireler ve müstakil evler tercih edilir. Her tür için geniş bir seçenek yelpazesi mevcuttur.', 'bilgi', 'low', 'karasu'),
('Karasu''da ev alırken emlak danışmanı gerekli mi?', 'Evet, profesyonel emlak danışmanı ile çalışmak önemlidir. Piyasa bilgisi, fiyat analizi, tapu süreci, yasal danışmanlık ve güvenli işlem için uzman desteği gereklidir. Tüm süreçte yanınızda olur.', 'karar_verme', 'medium', 'karasu'),
('Karasu''da ev alırken vergi yükümlülükleri nelerdir?', 'Emlak alımında emlak alım vergisi, tapu harcı ve noter ücretleri ödenir. Vergi oranları değişkendir. Güncel vergi bilgileri için mali müşavir veya emlak danışmanınızla görüşmeniz önerilir.', 'bilgi', 'low', 'karasu'),
('Karasu''da ev alırken deprem riski var mı?', 'Türkiye''nin birçok bölgesi gibi Karasu da deprem riski taşır. Ev alırken yapı durumu, deprem yönetmeliğine uygunluk ve zemin etüdü kontrol edilmelidir. Güvenli yapılar tercih edilmelidir.', 'risk', 'high', 'karasu'),
('Karasu''da ev alırken kış aylarında ne yapılmalı?', 'Yazlık evler kış aylarında bakım gerektirir. Su tesisatının boşaltılması, ısıtma sistemlerinin kontrolü, güvenlik önlemleri ve düzenli bakım önemlidir. Sürekli oturum için merkez bölgeler daha uygundur.', 'bilgi', 'low', 'karasu'),
('Karasu''da ev alırken komşuluk ilişkileri nasıl?', 'Karasu genellikle sakin ve huzurlu bir yaşam sunar. Komşuluk ilişkileri genellikle iyidir. Özellikle merkez mahallelerde sosyal yaşam canlıdır. Mahalle seçerken bu faktörü de değerlendirmek önemlidir.', 'bilgi', 'low', 'karasu'),
('Karasu''da ev alırken ulaşım imkanları yeterli mi?', 'Evet, Karasu''da ulaşım imkanları gelişmiştir. İstanbul''a yakınlık, otoyol erişimi, toplu taşıma araçları ve merkez konum avantajları vardır. Özellikle merkez mahallelerde ulaşım kolaylığı yüksektir.', 'bilgi', 'medium', 'karasu'),
('Karasu''da ev alırken okul ve sağlık tesisleri yeterli mi?', 'Karasu''da okul ve sağlık tesisleri mevcuttur. Merkez bölgelerde daha fazla seçenek bulunur. Özellikle sürekli oturum için bu tesislere yakınlık önemlidir. Güncel bilgi için emlak danışmanınızla görüşebilirsiniz.', 'bilgi', 'low', 'karasu'),
('Karasu''da ev alırken yatırım getirisi ne kadar?', 'Yatırım getirisi konum, ev tipi ve piyasa koşullarına göre değişir. Denize yakın konumlar yazlık kiralama geliri sağlar. Uzun vadede değer artışı beklentisi vardır. Detaylı analiz için profesyonel danışmanlık alınması önerilir.', 'yatirim', 'medium', 'karasu'),

-- KOCAALİ Q&As (20)
('Kocaali''de satılık ev almak mantıklı mı?', 'Evet, Kocaali''de satılık ev almak mantıklıdır. Daha uygun fiyatlı seçenekler, sakin yaşam, doğal güzellikler ve yatırım potansiyeli sunar. Karasu''ya göre daha uygun giriş fiyatları ile yatırım yapılabilir.', 'karar_verme', 'high', 'kocaali'),
('Kocaali''de ev fiyatları neden Karasu''dan daha uygun?', 'Kocaali, Karasu''ya göre daha az gelişmiş altyapı ve daha düşük turizm potansiyeline sahiptir. Bu nedenle fiyatlar genellikle daha uygun seviyededir. Ortalama fiyat aralığı 400.000 TL ile 2.500.000 TL arasındadır.', 'bilgi', 'high', 'kocaali'),
('Kocaali mi Karasu mu yatırım için daha avantajlı?', 'Her iki bölge de kendine özgü avantajlar sunar. Kocaali daha uygun giriş fiyatları ve sakin yaşam sunarken, Karasu daha gelişmiş altyapı ve yüksek turizm potansiyeline sahiptir. Yatırım tercihi bütçe ve hedeflere göre değişir.', 'karsilastirma', 'high', 'kocaali'),
('Kocaali''de ev alırken nelere dikkat edilmeli?', 'Konum, fiyat, bina yaşı, yapı durumu, tapu durumu, denize yakınlık, ulaşım imkanları ve sosyal altyapı dikkate alınmalıdır. Özellikle gelişmekte olan bölgelerde gelecek projeleri de değerlendirmek önemlidir.', 'risk', 'high', 'kocaali'),
('Kocaali''de hangi mahalleler öne çıkıyor?', 'Merkez mahalleler ve sahile yakın bölgeler öne çıkmaktadır. Denize erişimi olan mahalleler yazlık arayanlar için tercih edilirken, merkez bölgeler kalıcı yaşam için daha uygundur. Her mahallenin kendine özgü avantajları vardır.', 'bilgi', 'medium', 'kocaali'),
('Kocaali''de yazlık mı sürekli yaşam mı tercih ediliyor?', 'Kocaali''de hem yazlık hem de sürekli yaşam tercihleri görülmektedir. Yaz aylarında nüfus artışı yaşanırken, son yıllarda kalıcı yaşam tercih edenlerin sayısı da artmaktadır. Her iki seçenek için uygun seçenekler mevcuttur.', 'karar_verme', 'medium', 'kocaali'),
('Kocaali''de ev alırken yatırım potansiyeli var mı?', 'Evet, Kocaali yatırım potansiyeli taşır. Özellikle denize yakın bölgeler ve gelişmekte olan mahalleler uzun vadeli yatırımcılar için ilgi çekici olabilir. Daha uygun giriş fiyatları ile yatırım yapılabilir.', 'yatirim', 'high', 'kocaali'),
('Kocaali''de ev fiyatları gelecekte artacak mı?', 'Gelişmekte olan bölge olduğu için uzun vadede fiyat artışı beklentisi vardır. Özellikle altyapı yatırımları ve yeni projeler bölgenin değerini artırabilir. Ancak piyasa koşulları değişkendir.', 'yatirim', 'medium', 'kocaali'),
('Kocaali''de ev alırken ulaşım kolay mı?', 'Kocaali''de ulaşım imkanları mevcuttur. Merkeze yaklaşık 1-2 km mesafede toplu taşıma araçlarına erişim kolaydır. Özel araç ile İstanbul''a ulaşım mümkündür. Gelişen ulaşım ağı avantajı vardır.', 'bilgi', 'medium', 'kocaali'),
('Kocaali''de ev alırken sosyal yaşam nasıl?', 'Kocaali sakin ve huzurlu bir sosyal yaşam sunar. Temel ihtiyaçlar karşılanabilir, sosyal tesisler artmaktadır. Yaz aylarında daha canlı bir ortam vardır. Merkez bölgelerde daha fazla seçenek bulunur.', 'bilgi', 'low', 'kocaali'),
('Kocaali''de hangi ev türleri bulunuyor?', 'Kocaali''de müstakil evler, daireler, villalar ve yazlık evler bulunmaktadır. Denize yakın konumlarda yazlık evler, merkez bölgelerde daireler ve müstakil evler tercih edilir. Geniş bir seçenek yelpazesi mevcuttur.', 'bilgi', 'low', 'kocaali'),
('Kocaali''de ev alırken kredi kullanılabilir mi?', 'Evet, Kocaali''de kredi ile ev alınabilir. Banka kredisi ve peşinat seçenekleri mevcuttur. Genellikle ev değerinin %70-80''i kadar kredi kullanılabilir. Kredi başvuru süreci için emlak danışmanınızla görüşebilirsiniz.', 'bilgi', 'medium', 'kocaali'),
('Kocaali''de ev alırken tapu süreci nasıl?', 'Tapu süreci genellikle 1-2 hafta sürer. Satıcı ve alıcı noterde buluşur, tapu devri yapılır. Gerekli belgeler: kimlik, vergi levhası, tapu, ruhsat. Profesyonel emlak danışmanı tüm süreci yönetir.', 'bilgi', 'low', 'kocaali'),
('Kocaali''de ev alırken deprem riski var mı?', 'Türkiye''nin birçok bölgesi gibi Kocaali de deprem riski taşır. Ev alırken yapı durumu, deprem yönetmeliğine uygunluk ve zemin etüdü kontrol edilmelidir. Güvenli yapılar tercih edilmelidir.', 'risk', 'high', 'kocaali'),
('Kocaali''de ev alırken yatırım getirisi ne kadar?', 'Yatırım getirisi konum, ev tipi ve piyasa koşullarına göre değişir. Denize yakın konumlar yazlık kiralama geliri sağlar. Uzun vadede değer artışı beklentisi vardır. Detaylı analiz için profesyonel danışmanlık alınması önerilir.', 'yatirim', 'medium', 'kocaali'),
('Kocaali''de ev alırken komşuluk ilişkileri nasıl?', 'Kocaali genellikle sakin ve huzurlu bir yaşam sunar. Komşuluk ilişkileri genellikle iyidir. Özellikle merkez mahallelerde sosyal yaşam canlıdır. Mahalle seçerken bu faktörü de değerlendirmek önemlidir.', 'bilgi', 'low', 'kocaali'),
('Kocaali''de ev alırken okul ve sağlık tesisleri var mı?', 'Kocaali''de okul ve sağlık tesisleri mevcuttur. Merkez bölgelerde daha fazla seçenek bulunur. Özellikle sürekli oturum için bu tesislere yakınlık önemlidir. Güncel bilgi için emlak danışmanınızla görüşebilirsiniz.', 'bilgi', 'low', 'kocaali'),
('Kocaali''de ev alırken yeni projeler emlak piyasasını etkiliyor mu?', 'Evet, Kocaali''deki yeni konut ve altyapı projeleri bölgenin emlak piyasasını olumlu yönde etkileyebilir. Özellikle sahil düzenlemeleri ve ulaşım iyileştirmeleri çevresindeki konutlara olan ilgiyi artırabilir.', 'yatirim', 'medium', 'kocaali'),
('Kocaali''de ev alırken kış aylarında ne yapılmalı?', 'Yazlık evler kış aylarında bakım gerektirir. Su tesisatının boşaltılması, ısıtma sistemlerinin kontrolü, güvenlik önlemleri ve düzenli bakım önemlidir. Sürekli oturum için merkez bölgeler daha uygundur.', 'bilgi', 'low', 'kocaali'),
('Kocaali''de ev alırken emlak danışmanı gerekli mi?', 'Evet, profesyonel emlak danışmanı ile çalışmak önemlidir. Piyasa bilgisi, fiyat analizi, tapu süreci, yasal danışmanlık ve güvenli işlem için uzman desteği gereklidir. Tüm süreçte yanınızda olur.', 'karar_verme', 'medium', 'kocaali')
ON CONFLICT DO NOTHING;
